version: "3.8"

volumes:
  db-data:

services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    container_name: db
    volumes:
      - ./images/db/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=testdb
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  app:
    build:
      context: ./images/app
    container_name: app
    ports:
      - "8080:8080"
    command: 
      - /app/gradlew
      - bootRun
    depends_on:
      - db

