version: "3.8"

volumes:
  db-data:

services:
  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./images/db/initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testdb
#      - LANG=ja_JP.utf8

  app:
    image: amazoncorretto:17
#    build:
#      context: ./images/app
    container_name: app
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
#    command: 
#      - /app/gradlew
#      - bootRun
    depends_on:
      - db

